# Generated by Django 6.0.3 on 2026-03-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(help_text='The name of the opposing team.', max_length=100)),
                ('home_away', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], help_text='Whether the match is home or away.', max_length=10)),
                ('match_date', models.DateField(help_text='The scheduled calendar date of the match.')),
                ('kickoff_time', models.TimeField(blank=True, help_text='The scheduled kickoff time of the match.', null=True)),
                ('round_label', models.CharField(blank=True, help_text="Optional round label, such as 'Round 1' or 'Semi Final'.", max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('played', 'Played'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned')], default='upcoming', help_text='The current status of the match.', max_length=20)),
                ('team_score', models.PositiveIntegerField(blank=True, help_text='The number of goals scored by the club team.', null=True)),
                ('opponent_score', models.PositiveIntegerField(blank=True, help_text='The number of goals scored by the opposing team.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this match record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this match record was last updated.')),
                ('competition', models.ForeignKey(help_text='The competition this match is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('season', models.ForeignKey(help_text='The season that this match belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='seasons.season')),
                ('team', models.ForeignKey(help_text='The club team that this match belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.team')),
                ('venue', models.ForeignKey(blank=True, help_text='The venue where the match is scheduled to be played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_date', 'kickoff_time', 'team__name', 'opponent_name'],
            },
        ),
    ]
