# Generated by Django 6.0.3 on 2026-03-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('opponents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date', 'kickoff_time', 'team__name', 'opponent__name'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_name',
        ),
        migrations.AddField(
            model_name='match',
            name='half_length_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Scheduled length of each half in minutes.'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_length_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Total scheduled match length in minutes.'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(blank=True, help_text='The opposing team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='opponents.opponentteam'),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_opponent_score',
            field=models.PositiveIntegerField(blank=True, help_text='Penalty shootout goals scored by the opponent, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_team_score',
            field=models.PositiveIntegerField(blank=True, help_text='Penalty shootout goals scored by the club team, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='result_resolution',
            field=models.CharField(blank=True, choices=[('regular_time', 'Regular time'), ('draw', 'Draw'), ('extra_time', 'Extra time'), ('penalties', 'Penalties')], help_text='How the final result of the match was resolved.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_score',
            field=models.PositiveIntegerField(blank=True, help_text='The number of goals scored by the opposing team in normal or extra time.', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_score',
            field=models.PositiveIntegerField(blank=True, help_text='The number of goals scored by the club team in normal or extra time.', null=True),
        ),
    ]
