# Generated by Django 6.0.3 on 2026-03-10 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_alter_lineupentry_position_label'),
        ('matches', '0002_alter_match_options_remove_match_opponent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event_capture_mode',
            field=models.CharField(choices=[('full_timeline', 'Full timeline'), ('key_events_only', 'Key events only')], default='full_timeline', help_text='Defines whether this match has a full coded event timeline or only key events.', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_the_match',
            field=models.ForeignKey(blank=True, help_text='Optional Player of the Match selection from the club lineup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_of_match_awards', to='lineups.lineupentry'),
        ),
    ]
