# Generated by Django 6.0.3 on 2026-03-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Current ladder position of the team.')),
                ('played', models.PositiveIntegerField(default=0, help_text='Number of matches played.')),
                ('won', models.PositiveIntegerField(default=0, help_text='Number of matches won.')),
                ('drawn', models.PositiveIntegerField(default=0, help_text='Number of matches drawn.')),
                ('lost', models.PositiveIntegerField(default=0, help_text='Number of matches lost.')),
                ('goals_for', models.PositiveIntegerField(default=0, help_text='Total goals scored by the team.')),
                ('goals_against', models.PositiveIntegerField(default=0, help_text='Total goals conceded by the team.')),
                ('goal_difference', models.IntegerField(default=0, help_text='Goal difference, typically goals for minus goals against.')),
                ('points', models.PositiveIntegerField(default=0, help_text='Total competition points.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this standing record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this standing record was last updated.')),
                ('competition', models.ForeignKey(help_text='The competition that this standing record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competitions.competition')),
                ('season', models.ForeignKey(help_text='The season that this standing record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='seasons.season')),
                ('team', models.ForeignKey(help_text='The team that this standing record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
                'ordering': ['season__name', 'competition__name', 'position', 'team__name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'season', 'competition'), name='unique_team_standing_per_season_competition'), models.UniqueConstraint(fields=('season', 'competition', 'position'), name='unique_position_per_season_competition')],
            },
        ),
    ]
