# Generated by Django 6.0.3 on 2026-03-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['participant__season__name', 'participant__competition__name', 'position', 'participant__display_name', 'participant__id'], 'verbose_name': 'Standing', 'verbose_name_plural': 'Standings'},
        ),
        migrations.RemoveConstraint(
            model_name='standing',
            name='unique_team_standing_per_season_competition',
        ),
        migrations.RemoveConstraint(
            model_name='standing',
            name='unique_position_per_season_competition',
        ),
        migrations.AddField(
            model_name='standing',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='The competition participant that this standing record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='participants.competitionparticipant'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_against',
            field=models.PositiveIntegerField(default=0, help_text='Total goals conceded by the participant.'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_for',
            field=models.PositiveIntegerField(default=0, help_text='Total goals scored by the participant.'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='position',
            field=models.PositiveIntegerField(help_text='Current ladder position of the participant.'),
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('participant',), name='unique_standing_per_participant'),
        ),
        migrations.RemoveField(
            model_name='standing',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='season',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='team',
        ),
    ]
