# Generated by Django 6.0.3 on 2026-03-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full venue name used throughout the site.', max_length=100)),
                ('short_name', models.CharField(blank=True, help_text='Optional shorter venue name for compact displays.', max_length=30)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the venue.', max_length=120)),
                ('address', models.CharField(blank=True, help_text='Optional street address for the venue.', max_length=255)),
                ('suburb', models.CharField(blank=True, help_text='Optional suburb or locality for the venue.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this venue is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this venue record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this venue record was last updated.')),
                ('club', models.ForeignKey(help_text='The club that manages or tracks this venue.', on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['club__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'name'), name='unique_venue_name_per_club'), models.UniqueConstraint(fields=('club', 'slug'), name='unique_venue_slug_per_club')],
            },
        ),
    ]
