# Generated by Django 6.0.3 on 2026-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full association name used throughout the site.', max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Optional shorter association name for compact displays.', max_length=30)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the association.', max_length=120, unique=True)),
                ('website_url', models.URLField(blank=True, help_text='Optional website URL for the association.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this association is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this association record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this association record was last updated.')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['name'],
            },
        ),
    ]
