# Generated by Django 6.0.3 on 2026-03-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineups', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('own_goal', 'Own goal'), ('yellow_card', 'Yellow card'), ('red_card', 'Red card'), ('substitution', 'Substitution')], help_text='The type of event recorded for the match.', max_length=20)),
                ('side', models.CharField(choices=[('club', 'Club'), ('opponent', 'Opponent')], default='club', help_text='Whether the event belongs to the club side or the opponent.', max_length=10)),
                ('minute', models.PositiveIntegerField(blank=True, help_text='The minute the event occurred in normal time.', null=True)),
                ('stoppage_minute', models.PositiveIntegerField(blank=True, help_text='Optional stoppage time minute added to the main match minute.', null=True)),
                ('opponent_player_name', models.CharField(blank=True, help_text='Optional opponent player name when no lineup entry exists.', max_length=100)),
                ('notes', models.CharField(blank=True, help_text='Optional notes providing extra context for the event.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order for events recorded at the same minute.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this event record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this event record was last updated.')),
                ('lineup_entry', models.ForeignKey(blank=True, help_text='The main lineup entry linked to this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_events', to='lineups.lineupentry')),
                ('match', models.ForeignKey(help_text='The match that this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('related_lineup_entry', models.ForeignKey(blank=True, help_text='An optional second lineup entry, mainly for substitutions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_events', to='lineups.lineupentry')),
            ],
            options={
                'verbose_name': 'Match event',
                'verbose_name_plural': 'Match events',
                'ordering': ['match__match_date', 'minute', 'stoppage_minute', 'sort_order', 'id'],
            },
        ),
    ]
