# Generated by Django 6.0.3 on 2026-03-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_matchcoachassignment'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='match_coach_assignment',
            field=models.ForeignKey(blank=True, help_text='Optional match coach assignment linked to this event, mainly for coach cards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='coaches.matchcoachassignment'),
        ),
    ]
