# Generated by Django 6.0.3 on 2026-03-09 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_matchevent_match_coach_assignment'),
        ('matches', '0002_alter_match_options_remove_match_opponent_name_and_more'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('caused_by', 'Caused by'), ('resulted_in', 'Resulted in'), ('assisted_by', 'Assisted by'), ('preceded_by', 'Preceded by'), ('followed_by', 'Followed by'), ('related', 'Related')], max_length=24)),
                ('sequence_index', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('from_event_id', 'sequence_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatchEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('recipient', 'Recipient'), ('target', 'Target'), ('assister', 'Assister'), ('goalkeeper', 'Goalkeeper'), ('winner', 'Winner'), ('loser', 'Loser'), ('fouler', 'Fouler'), ('fouled', 'Fouled'), ('card_receiver', 'Card receiver'), ('subbed_on', 'Subbed on'), ('subbed_off', 'Subbed off')], max_length=32)),
                ('display_name', models.CharField(blank=True, help_text='Use when you want to record a participant without linking a Player row.', max_length=120)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sequence_index', models.PositiveSmallIntegerField(default=0, help_text='Lets you store more than one participant for the same role.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('event_id', 'role', 'sequence_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatchEventQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Canonical machine-readable key, e.g. body_part or shot_on_target.', max_length=64)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('decimal', 'Decimal'), ('bool', 'Boolean'), ('team', 'Team'), ('player', 'Player'), ('event', 'Event')], max_length=16)),
                ('text_value', models.TextField(blank=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('sequence_index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('event_id', 'key', 'sequence_index', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ('match_id', 'period', 'minute', 'added_minute', 'second', 'sequence_index', 'id')},
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='lineup_entry',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='match_coach_assignment',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='opponent_player_name',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='related_lineup_entry',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='side',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='stoppage_minute',
        ),
        migrations.AddField(
            model_name='matchevent',
            name='added_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='For 90+3, store minute=90 and added_minute=3.'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='end_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='end_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('neutral', 'Neutral')], default='neutral', max_length=16),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='period',
            field=models.CharField(blank=True, choices=[('1H', '1st Half'), ('2H', '2nd Half'), ('ET1', 'Extra Time 1st ET Half'), ('ET2', '2nd ET Half'), ('PEN', 'Penalties')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='second',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='sequence_index',
            field=models.PositiveIntegerField(blank=True, help_text='Tie-break ordering when multiple events share the same timestamp.', null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='start_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='start_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team the event is attributed to for stat derivation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('kick_off', 'Kick off'), ('half_start', 'Half start'), ('half_end', 'Half end'), ('full_time', 'Full time'), ('extra_time_start', 'Extra time start'), ('extra_time_end', 'Extra time end'), ('penalties_start', 'Penalties start'), ('penalties_end', 'Penalties end'), ('carry', 'Carry'), ('dribble', 'Dribble'), ('cross', 'Cross'), ('through_ball', 'Through ball'), ('long_ball', 'Long ball'), ('shot', 'Shot'), ('goal', 'Goal'), ('own_goal', 'Own goal'), ('chance_created', 'Chance created'), ('assist', 'Assist'), ('key_pass', 'Key pass'), ('tackle', 'Tackle'), ('interception', 'Interception'), ('clearance', 'Clearance'), ('block', 'Block'), ('recovery', 'Recovery'), ('aerial_duel', 'Aerial duel'), ('ground_duel', 'Ground duel'), ('save', 'Save'), ('claim', 'Claim'), ('punch', 'Punch'), ('sweep', 'Sweep'), ('distribution', 'Distribution'), ('foul_committed', 'Foul committed'), ('foul_won', 'Foul won'), ('offside', 'Offside'), ('yellow_card', 'Yellow card'), ('red_card', 'Red card'), ('second_yellow_red', 'Second yellow then red'), ('substitution', 'Substitution'), ('corner_taken', 'Corner taken')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'period', 'minute', 'added_minute', 'second', 'sequence_index'], name='event_match_time_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'event_type'], name='event_match_type_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'team'], name='event_match_team_idx'),
        ),
        migrations.AddField(
            model_name='matcheventlink',
            name='from_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='events.matchevent'),
        ),
        migrations.AddField(
            model_name='matcheventlink',
            name='to_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='events.matchevent'),
        ),
        migrations.AddField(
            model_name='matcheventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.matchevent'),
        ),
        migrations.AddField(
            model_name='matcheventparticipant',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='players.player'),
        ),
        migrations.AddField(
            model_name='matcheventparticipant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matcheventqualifier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='events.matchevent'),
        ),
        migrations.AddField(
            model_name='matcheventqualifier',
            name='event_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.matchevent'),
        ),
        migrations.AddField(
            model_name='matcheventqualifier',
            name='player_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player'),
        ),
        migrations.AddField(
            model_name='matcheventqualifier',
            name='team_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='matcheventlink',
            index=models.Index(fields=['from_event', 'link_type'], name='event_link_from_idx'),
        ),
        migrations.AddIndex(
            model_name='matcheventlink',
            index=models.Index(fields=['to_event', 'link_type'], name='event_link_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='matcheventlink',
            constraint=models.UniqueConstraint(fields=('from_event', 'to_event', 'link_type', 'sequence_index'), name='uniq_event_link_triplet_seq'),
        ),
        migrations.AddIndex(
            model_name='matcheventparticipant',
            index=models.Index(fields=['event', 'role'], name='event_part_role_idx'),
        ),
        migrations.AddIndex(
            model_name='matcheventparticipant',
            index=models.Index(fields=['player'], name='event_part_player_idx'),
        ),
        migrations.AddConstraint(
            model_name='matcheventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'role', 'sequence_index'), name='uniq_event_part_role_seq'),
        ),
        migrations.AddIndex(
            model_name='matcheventqualifier',
            index=models.Index(fields=['event', 'key'], name='event_qual_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='matcheventqualifier',
            constraint=models.UniqueConstraint(fields=('event', 'key', 'sequence_index'), name='uniq_event_qual_key_seq'),
        ),
    ]
