# Generated by Django 6.0.3 on 2026-03-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_matcheventlink_matcheventparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('kick_off', 'Kick off'), ('half_start', 'Half start'), ('half_end', 'Half end'), ('full_time', 'Full time'), ('extra_time_start', 'Extra time start'), ('extra_time_end', 'Extra time end'), ('penalties_start', 'Penalties start'), ('penalties_end', 'Penalties end'), ('carry', 'Carry'), ('dribble', 'Dribble'), ('cross', 'Cross'), ('through_ball', 'Through ball'), ('long_ball', 'Long ball'), ('shot', 'Shot'), ('goal', 'Goal'), ('own_goal', 'Own goal'), ('chance_created', 'Chance created'), ('assist', 'Assist'), ('key_pass', 'Key pass'), ('tackle', 'Tackle'), ('interception', 'Interception'), ('clearance', 'Clearance'), ('block', 'Block'), ('recovery', 'Recovery'), ('aerial_duel', 'Aerial duel'), ('ground_duel', 'Ground duel'), ('save', 'Save'), ('claim', 'Claim'), ('punch', 'Punch'), ('sweep', 'Sweep'), ('distribution', 'Distribution'), ('foul_committed', 'Foul committed'), ('foul_won', 'Foul won'), ('offside', 'Offside'), ('yellow_card', 'Yellow card'), ('red_card', 'Red card'), ('second_yellow_red', 'Second yellow then red'), ('substitution', 'Substitution'), ('corner_taken', 'Corner taken')], max_length=32),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='period',
            field=models.CharField(choices=[('1H', '1st Half'), ('2H', '2nd Half'), ('ET1', 'Extra Time 1st ET Half'), ('ET2', '2nd ET Half'), ('PEN', 'Penalties')], max_length=4),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='sequence_index',
            field=models.PositiveIntegerField(default=0, help_text='Tie-break ordering when multiple events share the same timestamp.'),
        ),
    ]
