# Generated by Django 6.0.3 on 2026-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_matchevent_event_type_alter_matchevent_period_and_more'),
        ('matches', '0002_alter_match_options_remove_match_opponent_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchevent',
            name='event_match_team_idx',
        ),
        migrations.AddField(
            model_name='matchevent',
            name='team_side',
            field=models.CharField(choices=[('club', 'Club'), ('opponent', 'Opponent'), ('neutral', 'Neutral')], default='club', help_text='Which side this event is attributed to.', max_length=10),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('kick_off', 'Kick off'), ('half_start', 'Half start'), ('half_end', 'Half end'), ('full_time', 'Full time'), ('extra_time_start', 'Extra time start'), ('extra_time_end', 'Extra time end'), ('penalties_start', 'Penalties start'), ('penalties_end', 'Penalties end'), ('pass', 'Pass'), ('carry', 'Carry'), ('dribble', 'Dribble'), ('shot', 'Shot'), ('own_goal', 'Own goal'), ('tackle', 'Tackle'), ('interception', 'Interception'), ('clearance', 'Clearance'), ('block', 'Block'), ('ball_recovery', 'Ball recovery'), ('aerial_duel', 'Aerial duel'), ('save', 'Save'), ('claim', 'Claim'), ('foul_committed', 'Foul committed'), ('foul_won', 'Foul won'), ('offside', 'Offside'), ('card', 'Card'), ('substitution', 'Substitution')], max_length=32),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='outcome',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('won', 'Won'), ('lost', 'Lost'), ('scored', 'Scored'), ('saved', 'Saved'), ('blocked', 'Blocked'), ('off_target', 'Off target'), ('neutral', 'Neutral')], default='neutral', max_length=16),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'team_side'], name='event_match_side_idx'),
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='team',
        ),
    ]
