# Generated by Django 6.0.3 on 2026-03-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_matchcoachassignment'),
        ('events', '0005_remove_matchevent_event_match_team_idx_and_more'),
        ('lineups', '0002_alter_lineupentry_position_label'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matcheventparticipant',
            name='event_part_player_idx',
        ),
        migrations.AddField(
            model_name='matcheventparticipant',
            name='lineup_entry',
            field=models.ForeignKey(blank=True, help_text='Use for club-side player participants tied to this specific match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='lineups.lineupentry'),
        ),
        migrations.AddField(
            model_name='matcheventparticipant',
            name='match_coach_assignment',
            field=models.ForeignKey(blank=True, help_text='Use for coach participants tied to this specific match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='coaches.matchcoachassignment'),
        ),
        migrations.AlterField(
            model_name='matcheventparticipant',
            name='display_name',
            field=models.CharField(blank=True, help_text='Use when you want to record an opponent or unknown participant without linking a club-side lineup or coach record.', max_length=120),
        ),
        migrations.AddIndex(
            model_name='matcheventparticipant',
            index=models.Index(fields=['lineup_entry'], name='event_part_lineup_idx'),
        ),
        migrations.AddIndex(
            model_name='matcheventparticipant',
            index=models.Index(fields=['match_coach_assignment'], name='event_part_coach_idx'),
        ),
        migrations.RemoveField(
            model_name='matcheventparticipant',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matcheventparticipant',
            name='team',
        ),
    ]
