# Generated by Django 6.0.3 on 2026-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_matcheventparticipant_event_part_player_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matcheventqualifier',
            name='key',
            field=models.CharField(choices=[('body_part', 'Body part'), ('under_pressure', 'Under pressure'), ('big_chance', 'Big chance'), ('pass_length', 'Pass length'), ('pass_profile', 'Pass profile'), ('pass_height', 'Pass height'), ('pass_direction', 'Pass direction'), ('progressive', 'Progressive'), ('restart_type', 'Restart type'), ('restart_side', 'Restart side'), ('free_kick_profile', 'Free kick profile'), ('shot_zone', 'Shot zone'), ('shot_on_target', 'Shot on target'), ('shot_target_horizontal', 'Shot target horizontal'), ('shot_target_vertical', 'Shot target vertical'), ('hit_woodwork', 'Hit woodwork'), ('tackle_profile', 'Tackle profile'), ('foul_profile', 'Foul profile'), ('card_type', 'Card type'), ('card_reason', 'Card reason')], help_text='Controlled qualifier key for this event metadata row.', max_length=32),
        ),
    ]
