# Generated by Django 6.0.3 on 2026-03-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_matcheventlink_link_type'),
        ('opponents', '0002_opponentlineupentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcheventparticipant',
            name='opponent_lineup_entry',
            field=models.ForeignKey(blank=True, help_text='Use for opponent-side player participants tied to this specific match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='opponents.opponentlineupentry'),
        ),
    ]
