# Generated by Django 6.0.3 on 2026-03-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_matcheventparticipant_opponent_lineup_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matcheventlink',
            name='link_type',
            field=models.CharField(choices=[('created_shot', 'Created shot'), ('assist', 'Assist'), ('resulted_in_save', 'Resulted in save'), ('resulted_in_card', 'Resulted in card'), ('rebound_from', 'Rebound from'), ('related', 'Related')], max_length=24),
        ),
    ]
