# Generated by Django 6.0.3 on 2026-03-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_matcheventlink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('kick_off', 'Kick off'), ('half_start', 'Half start'), ('half_end', 'Half end'), ('full_time', 'Full time'), ('extra_time_start', 'Extra time start'), ('extra_time_end', 'Extra time end'), ('penalties_start', 'Penalties start'), ('penalties_end', 'Penalties end'), ('pass', 'Pass'), ('carry', 'Carry'), ('dribble', 'Dribble'), ('shot', 'Shot'), ('own_goal', 'Own goal'), ('tackle', 'Tackle'), ('interception', 'Interception'), ('clearance', 'Clearance'), ('block', 'Block'), ('ball_recovery', 'Ball recovery'), ('aerial_duel', 'Aerial duel'), ('save', 'Save'), ('claim', 'Claim'), ('foul_committed', 'Foul committed'), ('foul_won', 'Foul won'), ('offside', 'Offside'), ('card', 'Card'), ('position_change', 'Position change'), ('substitution', 'Substitution')], max_length=32),
        ),
        migrations.AlterField(
            model_name='matcheventqualifier',
            name='key',
            field=models.CharField(choices=[('body_part', 'Body part'), ('under_pressure', 'Under pressure'), ('big_chance', 'Big chance'), ('pass_length', 'Pass length'), ('pass_profile', 'Pass profile'), ('pass_height', 'Pass height'), ('pass_direction', 'Pass direction'), ('progressive', 'Progressive'), ('restart_type', 'Restart type'), ('restart_side', 'Restart side'), ('free_kick_profile', 'Free kick profile'), ('subbed_on_position', 'Subbed on position'), ('subbed_off_position', 'Subbed off position'), ('position_from', 'Position from'), ('position_to', 'Position to'), ('shot_zone', 'Shot zone'), ('shot_on_target', 'Shot on target'), ('shot_target_horizontal', 'Shot target horizontal'), ('shot_target_vertical', 'Shot target vertical'), ('hit_woodwork', 'Hit woodwork'), ('tackle_profile', 'Tackle profile'), ('foul_profile', 'Foul profile'), ('card_type', 'Card type'), ('card_reason', 'Card reason')], help_text='Controlled qualifier key for this event metadata row.', max_length=32),
        ),
    ]
