# Generated by Django 6.0.3 on 2026-03-07 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for the season, such as '2026' or '2025/26'.", max_length=50)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the season.', max_length=60)),
                ('start_date', models.DateField(blank=True, help_text='Optional start date for the season.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for the season.', null=True)),
                ('is_current', models.BooleanField(default=False, help_text="Indicates whether this is the club's current active season.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this season record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this season record was last updated.')),
                ('club', models.ForeignKey(help_text='The club that this season belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['club__name', '-start_date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'name'), name='unique_season_name_per_club'), models.UniqueConstraint(fields=('club', 'slug'), name='unique_season_slug_per_club')],
            },
        ),
    ]
