# Generated by Django 6.0.3 on 2026-03-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineups', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveIntegerField(default=0, help_text='Number of minutes played by the player in the match.')),
                ('goals', models.PositiveIntegerField(default=0, help_text='Number of goals scored by the player.')),
                ('assists', models.PositiveIntegerField(default=0, help_text='Number of assists recorded by the player.')),
                ('yellow_cards', models.PositiveIntegerField(default=0, help_text='Number of yellow cards received by the player.')),
                ('red_cards', models.PositiveIntegerField(default=0, help_text='Number of red cards received by the player.')),
                ('clean_sheet', models.BooleanField(default=False, help_text='Whether the player was part of a clean sheet.')),
                ('goals_conceded', models.PositiveIntegerField(default=0, help_text='Number of goals conceded while the player was on the field.')),
                ('saves', models.PositiveIntegerField(default=0, help_text='Number of saves made by the player, mainly for goalkeepers.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this stat record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this stat record was last updated.')),
                ('lineup_entry', models.ForeignKey(help_text='The lineup entry that these statistics belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='lineups.lineupentry')),
                ('match', models.ForeignKey(help_text='The match that these statistics belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match')),
            ],
            options={
                'verbose_name': 'Player match stat',
                'verbose_name_plural': 'Player match stats',
                'ordering': ['match__match_date', 'lineup_entry__registration__player__last_name', 'lineup_entry__registration__player__first_name'],
                'constraints': [models.UniqueConstraint(fields=('match', 'lineup_entry'), name='unique_player_stat_per_match_lineup')],
            },
        ),
    ]
