# Generated by Django 6.0.3 on 2026-03-07 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_competition_association_competition_competition_type_and_more'),
        ('opponents', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional custom display name for the participant in this competition.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this participant is currently active in the competition.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this participant record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this participant record was last updated.')),
                ('competition', models.ForeignKey(help_text='The competition this participant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('opponent_team', models.ForeignKey(blank=True, help_text='The external opponent team participating in this competition, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_participants', to='opponents.opponentteam')),
                ('season', models.ForeignKey(help_text='The season this participant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='seasons.season')),
                ('team', models.ForeignKey(blank=True, help_text='The club team participating in this competition, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_participants', to='teams.team')),
            ],
            options={
                'verbose_name': 'Competition participant',
                'verbose_name_plural': 'Competition participants',
                'ordering': ['season__name', 'competition__name', 'display_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('season', 'competition', 'team'), name='unique_team_participant_per_season_competition'), models.UniqueConstraint(fields=('season', 'competition', 'opponent_team'), name='unique_opponent_participant_per_season_competition')],
            },
        ),
    ]
