# Generated by Django 6.0.3 on 2026-03-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_coach', 'Head coach'), ('assistant_coach', 'Assistant coach'), ('team_manager', 'Team manager'), ('goalkeeper_coach', 'Goalkeeper coach'), ('other', 'Other')], default='head_coach', help_text="The coach's primary role for this team and season.", max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this registration is currently active.')),
                ('joined_on', models.DateField(blank=True, help_text='Optional date the coach joined the team for this season.', null=True)),
                ('left_on', models.DateField(blank=True, help_text='Optional date the coach left the team for this season.', null=True)),
                ('notes', models.CharField(blank=True, help_text="Optional notes about the coach's role or arrangement for the season.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this registration record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this registration record was last updated.')),
                ('coach', models.ForeignKey(help_text='The coach being registered.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='coaches.coach')),
                ('season', models.ForeignKey(help_text='The season the registration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='coach_registrations', to='seasons.season')),
                ('team', models.ForeignKey(help_text='The team the coach is registered to.', on_delete=django.db.models.deletion.CASCADE, related_name='coach_registrations', to='teams.team')),
            ],
            options={
                'verbose_name': 'Coach registration',
                'verbose_name_plural': 'Coach registrations',
                'ordering': ['season__name', 'team__name', 'coach__last_name', 'coach__first_name'],
                'constraints': [models.UniqueConstraint(fields=('coach', 'team', 'season'), name='unique_coach_team_season_registration')],
            },
        ),
    ]
