# Generated by Django 6.0.3 on 2026-03-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coachregistration'),
        ('matches', '0002_alter_match_options_remove_match_opponent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday_role', models.CharField(blank=True, choices=[('head_coach', 'Head coach'), ('assistant_coach', 'Assistant coach'), ('team_manager', 'Team manager'), ('goalkeeper_coach', 'Goalkeeper coach'), ('other', 'Other')], help_text='Optional matchday-specific role if it differs from the season registration role.', max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order for showing coaches on the match page.')),
                ('notes', models.CharField(blank=True, help_text="Optional notes about this coach's role for the match.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this assignment record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this assignment record was last updated.')),
                ('coach_registration', models.ForeignKey(help_text='The team-season coach registration assigned to the match.', on_delete=django.db.models.deletion.CASCADE, related_name='match_assignments', to='coaches.coachregistration')),
                ('match', models.ForeignKey(help_text='The match this coaching assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='matches.match')),
            ],
            options={
                'verbose_name': 'Match coach assignment',
                'verbose_name_plural': 'Match coach assignments',
                'ordering': ['-match__match_date', 'display_order', 'coach_registration__coach__last_name', 'coach_registration__coach__first_name'],
                'constraints': [models.UniqueConstraint(fields=('match', 'coach_registration'), name='unique_coach_registration_per_match')],
            },
        ),
    ]
