# Generated by Django 6.0.3 on 2026-03-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('starter', 'Starter'), ('substitute', 'Substitute')], help_text='Whether the player was named as a starter or substitute.', max_length=20)),
                ('position_label', models.CharField(blank=True, help_text='Optional position label such as GK, CB, CM, or ST.', max_length=30)),
                ('shirt_number', models.PositiveIntegerField(blank=True, help_text='Optional shirt number worn by the player for this match.', null=True)),
                ('is_captain', models.BooleanField(default=False, help_text='Indicates whether the player was captain for this match.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order for the lineup, useful for starters and bench order.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this lineup entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this lineup entry was last updated.')),
                ('match', models.ForeignKey(help_text='The match this lineup entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='matches.match')),
                ('registration', models.ForeignKey(help_text='The player registration used for this lineup entry.', on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='registrations.playerregistration')),
            ],
            options={
                'verbose_name': 'Lineup entry',
                'verbose_name_plural': 'Lineup entries',
                'ordering': ['match__match_date', 'role', 'sort_order', 'registration__player__last_name'],
                'constraints': [models.UniqueConstraint(fields=('match', 'registration'), name='unique_registration_per_match_lineup')],
            },
        ),
    ]
