# Generated by Django 6.0.3 on 2026-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupentry',
            name='position_label',
            field=models.CharField(blank=True, choices=[('GK', 'GK'), ('CB', 'CB'), ('RB', 'RB'), ('LB', 'LB'), ('RWB', 'RWB'), ('LWB', 'LWB'), ('CDM', 'CDM'), ('CM', 'CM'), ('RM', 'RM'), ('LM', 'LM'), ('CAM', 'CAM'), ('RW', 'RW'), ('LW', 'LW'), ('CF', 'CF'), ('RS', 'RS'), ('LS', 'LS'), ('ST', 'ST')], help_text="Optional position label for the player's role in this match.", max_length=10),
        ),
    ]
