# Generated by Django 6.0.3 on 2026-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full club name used throughout the site.', max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Optional shorter club name for compact displays.', max_length=30)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the club.', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this club record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this club record was last updated.')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
            },
        ),
    ]
