# Generated by Django 6.0.3 on 2026-03-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_number', models.PositiveIntegerField(blank=True, help_text='Optional squad number for the player in this team and season.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this registration is currently active.')),
                ('joined_on', models.DateField(blank=True, help_text='Optional date the player joined the team for this season.', null=True)),
                ('left_on', models.DateField(blank=True, help_text='Optional date the player left the team for this season.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this registration record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this registration record was last updated.')),
                ('player', models.ForeignKey(help_text='The player being registered.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='players.player')),
                ('season', models.ForeignKey(help_text='The season the registration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='seasons.season')),
                ('team', models.ForeignKey(help_text='The team the player is registered to.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='teams.team')),
            ],
            options={
                'verbose_name': 'Player registration',
                'verbose_name_plural': 'Player registrations',
                'ordering': ['season__name', 'team__name', 'player__last_name', 'player__first_name'],
                'constraints': [models.UniqueConstraint(fields=('player', 'team', 'season'), name='unique_player_team_season_registration')],
            },
        ),
    ]
