# Generated by Django 6.0.3 on 2026-03-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full competition name used throughout the site.', max_length=100)),
                ('short_name', models.CharField(blank=True, help_text='Optional shorter competition name for compact displays.', max_length=30)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the competition.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this competition record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this competition record was last updated.')),
                ('club', models.ForeignKey(help_text='The club that manages or tracks this competition.', on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['club__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'name'), name='unique_competition_name_per_club'), models.UniqueConstraint(fields=('club', 'slug'), name='unique_competition_slug_per_club')],
            },
        ),
    ]
