# Generated by Django 6.0.3 on 2026-03-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('clubs', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='association',
            field=models.ForeignKey(blank=True, help_text='The external association or organising body that manages this competition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='associations.association'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly'), ('preseason_friendly', 'Pre-season friendly')], default='league', help_text='The format or type of competition.', max_length=30),
        ),
        migrations.AlterField(
            model_name='competition',
            name='club',
            field=models.ForeignKey(help_text='The club that tracks this competition in the app.', on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='clubs.club'),
        ),
    ]
