# Generated by Django 6.0.3 on 2026-03-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Player's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="Player's last name.", max_length=50)),
                ('preferred_name', models.CharField(blank=True, help_text='Optional preferred name or nickname for display purposes.', max_length=50)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the player.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the player is currently active at the club.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this player record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this player record was last updated.')),
                ('club', models.ForeignKey(help_text='The club that this player belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['club__name', 'last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'slug'), name='unique_player_slug_per_club')],
            },
        ),
    ]
