# Generated by Django 6.0.3 on 2026-03-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full opponent team name used throughout the site.', max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Optional shorter opponent team name for compact displays.', max_length=30)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the opponent team.', max_length=120, unique=True)),
                ('suburb', models.CharField(blank=True, help_text='Optional suburb or locality for the opponent team.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this opponent team is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this opponent team record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this opponent team record was last updated.')),
                ('association', models.ForeignKey(blank=True, help_text='Optional association that the opponent team belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_teams', to='associations.association')),
            ],
            options={
                'verbose_name': 'Opponent team',
                'verbose_name_plural': 'Opponent teams',
                'ordering': ['name'],
            },
        ),
    ]
