# Generated by Django 6.0.3 on 2026-03-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_remove_match_opponent_name_and_more'),
        ('opponents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentLineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Opponent player name for this match. Leave blank only if shirt number alone is being used.', max_length=120)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, help_text='Optional opponent shirt number for this match.', null=True)),
                ('is_starter', models.BooleanField(default=True, help_text='Whether this opponent participant started the match.')),
                ('is_known', models.BooleanField(default=True, help_text="Use False for placeholder entries such as 'Unknown #0' when the exact opponent player identity is not known.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when this opponent lineup entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when this opponent lineup entry was last updated.')),
                ('match', models.ForeignKey(help_text='The match this opponent lineup entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='opponent_lineup_entries', to='matches.match')),
                ('opponent_team', models.ForeignKey(help_text='The opponent team this lineup entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='opponents.opponentteam')),
            ],
            options={
                'verbose_name': 'Opponent lineup entry',
                'verbose_name_plural': 'Opponent lineup entries',
                'ordering': ('match_id', 'opponent_team__name', 'shirt_number', 'display_name', 'id'),
                'indexes': [models.Index(fields=['match', 'opponent_team'], name='opp_lineup_match_team_idx'), models.Index(fields=['match', 'shirt_number'], name='opp_lineup_match_shirt_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('shirt_number__isnull', False)), fields=('match', 'opponent_team', 'shirt_number'), name='uniq_opponent_lineup_shirt_per_match')],
            },
        ),
    ]
